name: workflow for Codecov
on: [push]
jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]
        exclude:
          - os: ubuntu-latest
            python-version: 3.9
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@master
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: install HDF5 and h5py
        shell: bash -l {0}
        run: |
          conda install -c conda-forge fsspec numcodecs
          conda install "hdf5>=1.10.5"
          conda install gcc_linux-64
          pip install numpy cython pkgconfig
          HDF5_DIR=$CONDA pip install --no-binary=h5py h5py
      - name: install HDF5Zarr
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: run tests
        shell: bash -l {0}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
